/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import VectorImage from 'src/assets/images/Chat_Vector.png';
import Vector1Image from 'src/assets/images/Chat_Vector_1.png';
import Vector2Image from 'src/assets/images/Chat_Vector_2.png';
import Vector3Image from 'src/assets/images/Chat_Vector_3.png';
import Vector4Image from 'src/assets/images/Chat_Vector_4.png';
import Vector5Image from 'src/assets/images/Chat_Vector_5.png';
import Vector6Image from 'src/assets/images/Chat_Vector_6.png';
import Vector7Image from 'src/assets/images/Chat_Vector_7.png';
import Vector8Image from 'src/assets/images/Chat_Vector_8.png';
import Vector9Image from 'src/assets/images/Chat_Vector_9.png';
import Vector10Image from 'src/assets/images/Chat_Vector_10.png';
import Vector11Image from 'src/assets/images/Chat_Vector_11.png';
import Vector12Image from 'src/assets/images/Chat_Vector_12.png';
import Vector13Image from 'src/assets/images/Chat_Vector_13.png';
import Vector14Image from 'src/assets/images/Chat_Vector_14.png';
import Vector15Image from 'src/assets/images/Chat_Vector_15.png';
import Vector16Image from 'src/assets/images/Chat_Vector_16.png';
import Vector17Image from 'src/assets/images/Chat_Vector_17.png';
import Vector18Image from 'src/assets/images/Chat_Vector_18.png';
import Vector19Image from 'src/assets/images/Chat_Vector_19.png';
import Vector20Image from 'src/assets/images/Chat_Vector_20.png';
import Vector21Image from 'src/assets/images/Chat_Vector_21.png';
import Vector22Image from 'src/assets/images/Chat_Vector_22.png';
import Vector23Image from 'src/assets/images/Chat_Vector_23.png';
import Vector24Image from 'src/assets/images/Chat_Vector_24.png';
import Vector25Image from 'src/assets/images/Chat_Vector_25.png';
import Vector26Image from 'src/assets/images/Chat_Vector_26.png';
import Vector27Image from 'src/assets/images/Chat_Vector_27.png';
import Vector28Image from 'src/assets/images/Chat_Vector_28.png';
import Vector29Image from 'src/assets/images/Chat_Vector_29.png';
import Vector30Image from 'src/assets/images/Chat_Vector_30.png';
import Vector31Image from 'src/assets/images/Chat_Vector_31.png';
import Vector32Image from 'src/assets/images/Chat_Vector_32.png';
import Vector33Image from 'src/assets/images/Chat_Vector_33.png';
import Vector34Image from 'src/assets/images/Chat_Vector_34.png';
import Vector35Image from 'src/assets/images/Chat_Vector_35.png';
import Vector36Image from 'src/assets/images/Chat_Vector_36.png';
import Vector37Image from 'src/assets/images/Chat_Vector_37.png';
import Vector38Image from 'src/assets/images/Chat_Vector_38.png';
import Vector39Image from 'src/assets/images/Chat_Vector_39.png';
import Vector40Image from 'src/assets/images/Chat_Vector_40.png';
import Vector41Image from 'src/assets/images/Chat_Vector_41.png';
import Vector42Image from 'src/assets/images/Chat_Vector_42.png';
import Icon1Image from 'src/assets/images/Chat_Icon.png';
import ShapeImage from 'src/assets/images/Chat_Shape.png';
import { styled } from '@mui/material/styles';
import StylesBackgroundsTransparent from 'src/components/StylesBackgroundsTransparent/StylesBackgroundsTransparent';
import { ChatProps } from 'src/types';

const Chat1: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `40px`,
  boxSizing: `border-box`,
  height: 'auto',
  width: 'fit-content',
});

const Frame289474: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `12px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Cell: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `64px`,
  width: `390px`,
  margin: `0px`,
});

const Background: any = styled(StylesBackgroundsTransparent)(
  ({ theme }: any) => ({
    width: `390px`,
    height: `64px`,
    position: `absolute`,
    left: `0px`,
    top: `0px`,
  })
);

const Container: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `264px`,
  height: `38px`,
  left: `68px`,
  top: `9px`,
});

const Subtitle: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `-0.07999999821186066px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `18px`,
});

const Title: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(37, 37, 37, 0.6)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `600`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Q20: any = styled('div')({
  borderRadius: `200px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  height: `40px`,
  left: `16px`,
  top: `7px`,
  overflow: `hidden`,
});

const Group: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  height: `51.88px`,
  left: `0px`,
  top: `0px`,
});

const Vector: any = styled('img')({
  height: `40px`,
  width: `40px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group1: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `20.65px`,
  height: `34.38px`,
  left: `8px`,
  top: `8px`,
});

const Vector1: any = styled('img')({
  height: `6.25px`,
  width: `6.25px`,
  position: `absolute`,
  left: `0px`,
  top: `12px`,
});

const Vector2: any = styled('img')({
  height: `16.88px`,
  width: `10.63px`,
  position: `absolute`,
  left: `3px`,
  top: `18px`,
});

const Vector3: any = styled('img')({
  height: `12.5px`,
  width: `9.37px`,
  position: `absolute`,
  left: `4px`,
  top: `16px`,
});

const Vector4: any = styled('img')({
  height: `26.87px`,
  width: `18.55px`,
  position: `absolute`,
  left: `2px`,
  top: `0px`,
});

const Vector5: any = styled('img')({
  height: `1.25px`,
  width: `1.88px`,
  position: `absolute`,
  left: `14px`,
  top: `18px`,
});

const Group2: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `25px`,
  height: `16.25px`,
  left: `4px`,
  top: `36px`,
});

const Vector6: any = styled('img')({
  height: `14.38px`,
  width: `25px`,
  position: `absolute`,
  left: `0px`,
  top: `2px`,
});

const Vector7: any = styled('img')({
  height: `2.5px`,
  width: `11.88px`,
  position: `absolute`,
  left: `6px`,
  top: `1px`,
});

const Vector8: any = styled('img')({
  height: `2.19px`,
  width: `11.88px`,
  position: `absolute`,
  left: `6px`,
  top: `1px`,
});

const Vector9: any = styled('img')({
  height: `1.88px`,
  width: `12.5px`,
  position: `absolute`,
  left: `6px`,
  top: `0px`,
});

const Group3: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `22.5px`,
  height: `36.25px`,
  left: `8px`,
  top: `4px`,
});

const Vector10: any = styled('img')({
  height: `36.25px`,
  width: `22.5px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector11: any = styled('img')({
  height: `3.75px`,
  width: `6.96px`,
  position: `absolute`,
  left: `18px`,
  top: `28px`,
});

const Vector12: any = styled('img')({
  height: `3.15px`,
  width: `5.04px`,
  position: `absolute`,
  left: `18px`,
  top: `29px`,
});

const Vector13: any = styled('img')({
  height: `1.25px`,
  width: `6.25px`,
  position: `absolute`,
  left: `19px`,
  top: `28px`,
});

const Group4: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `8.13px`,
  height: `2.5px`,
  left: `19px`,
  top: `23px`,
});

const Vector14: any = styled('img')({
  height: `2.5px`,
  width: `1.88px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector15: any = styled('img')({
  height: `2.5px`,
  width: `1.88px`,
  position: `absolute`,
  left: `6px`,
  top: `0px`,
});

const Cell1: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `64px`,
  width: `390px`,
  margin: `0px`,
});

const Background1: any = styled(StylesBackgroundsTransparent)(
  ({ theme }: any) => ({
    width: `390px`,
    height: `64px`,
    position: `absolute`,
    left: `0px`,
    top: `0px`,
  })
);

const Container1: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `126px`,
  height: `38.2px`,
  left: `68px`,
  top: `9px`,
});

const Subtitle1: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `-0.07999999821186066px`,
  textDecoration: `none`,
  lineHeight: `18px`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `20px`,
});

const Title1: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(37, 37, 37, 0.6)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `600`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Q21: any = styled('div')({
  borderRadius: `200px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  height: `40px`,
  left: `16px`,
  top: `9px`,
  overflow: `hidden`,
});

const Group5: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `42.07px`,
  height: `51.88px`,
  left: `-2px`,
  top: `0px`,
});

const Vector16: any = styled('img')({
  height: `40px`,
  width: `40px`,
  position: `absolute`,
  left: `2px`,
  top: `0px`,
});

const Group6: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `20.65px`,
  height: `34.38px`,
  left: `10px`,
  top: `8px`,
});

const Vector17: any = styled('img')({
  height: `6.25px`,
  width: `6.25px`,
  position: `absolute`,
  left: `0px`,
  top: `12px`,
});

const Vector18: any = styled('img')({
  height: `16.88px`,
  width: `10.63px`,
  position: `absolute`,
  left: `3px`,
  top: `18px`,
});

const Vector19: any = styled('img')({
  height: `13.38px`,
  width: `10.12px`,
  position: `absolute`,
  left: `4px`,
  top: `16px`,
});

const Vector20: any = styled('img')({
  height: `27.19px`,
  width: `18.55px`,
  position: `absolute`,
  left: `2px`,
  top: `0px`,
});

const Vector21: any = styled('img')({
  height: `1.25px`,
  width: `1.88px`,
  position: `absolute`,
  left: `14px`,
  top: `18px`,
});

const Group7: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `25px`,
  height: `14.38px`,
  left: `6px`,
  top: `38px`,
});

const Vector22: any = styled('img')({
  height: `14.38px`,
  width: `25px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group8: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `33.32px`,
  height: `27.01px`,
  left: `0px`,
  top: `4px`,
});

const Vector23: any = styled('img')({
  height: `22.93px`,
  width: `10.2px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector24: any = styled('img')({
  height: `6.65px`,
  width: `5.86px`,
  position: `absolute`,
  left: `8px`,
  top: `4px`,
});

const Vector25: any = styled('img')({
  height: `26.44px`,
  width: `25px`,
  position: `absolute`,
  left: `8px`,
  top: `1px`,
});

const Vector26: any = styled('img')({
  height: `2.5px`,
  width: `1.88px`,
  position: `absolute`,
  left: `21px`,
  top: `23px`,
});

const Vector27: any = styled('img')({
  height: `2.5px`,
  width: `1.88px`,
  position: `absolute`,
  left: `27px`,
  top: `23px`,
});

const Group9: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `14.38px`,
  height: `1.88px`,
  left: `17px`,
  top: `24px`,
});

const Vector28: any = styled('img')({
  height: `1.88px`,
  width: `3.13px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector29: any = styled('img')({
  height: `1.88px`,
  width: `2.5px`,
  position: `absolute`,
  left: `12px`,
  top: `0px`,
});

const Cell2: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `64px`,
  width: `390px`,
  margin: `0px`,
});

const Background2: any = styled(StylesBackgroundsTransparent)(
  ({ theme }: any) => ({
    width: `390px`,
    height: `64px`,
    position: `absolute`,
    left: `0px`,
    top: `0px`,
  })
);

const Container2: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `223px`,
  height: `38.2px`,
  left: `68px`,
  top: `9px`,
});

const Subtitle2: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `-0.07999999821186066px`,
  textDecoration: `none`,
  lineHeight: `18px`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `20px`,
});

const Title2: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(37, 37, 37, 0.6)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `600`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Q22: any = styled('div')({
  borderRadius: `200px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  height: `40px`,
  left: `16px`,
  top: `7px`,
  overflow: `hidden`,
});

const Group10: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  height: `51.88px`,
  left: `0px`,
  top: `0px`,
});

const Vector30: any = styled('img')({
  height: `40px`,
  width: `40px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group11: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `20.65px`,
  height: `34.38px`,
  left: `8px`,
  top: `8px`,
});

const Vector31: any = styled('img')({
  height: `6.25px`,
  width: `6.25px`,
  position: `absolute`,
  left: `0px`,
  top: `12px`,
});

const Vector32: any = styled('img')({
  height: `16.88px`,
  width: `10.63px`,
  position: `absolute`,
  left: `3px`,
  top: `18px`,
});

const Vector33: any = styled('img')({
  height: `12.5px`,
  width: `9.37px`,
  position: `absolute`,
  left: `4px`,
  top: `16px`,
});

const Vector34: any = styled('img')({
  height: `26.87px`,
  width: `18.55px`,
  position: `absolute`,
  left: `2px`,
  top: `0px`,
});

const Vector35: any = styled('img')({
  height: `1.25px`,
  width: `1.88px`,
  position: `absolute`,
  left: `14px`,
  top: `18px`,
});

const Group12: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `25px`,
  height: `14.38px`,
  left: `4px`,
  top: `38px`,
});

const Vector36: any = styled('img')({
  height: `14.38px`,
  width: `25px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector37: any = styled('img')({
  height: `19.84px`,
  width: `25.03px`,
  position: `absolute`,
  left: `7px`,
  top: `3px`,
});

const Vector38: any = styled('img')({
  height: `3.75px`,
  width: `6.96px`,
  position: `absolute`,
  left: `18px`,
  top: `28px`,
});

const Vector39: any = styled('img')({
  height: `3.15px`,
  width: `5.04px`,
  position: `absolute`,
  left: `18px`,
  top: `29px`,
});

const Vector40: any = styled('img')({
  height: `1.25px`,
  width: `6.25px`,
  position: `absolute`,
  left: `19px`,
  top: `28px`,
});

const Group13: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `8.13px`,
  height: `2.5px`,
  left: `19px`,
  top: `23px`,
});

const Vector41: any = styled('img')({
  height: `2.5px`,
  width: `1.88px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector42: any = styled('img')({
  height: `2.5px`,
  width: `1.88px`,
  position: `absolute`,
  left: `6px`,
  top: `0px`,
});

const Input1: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `64px`,
  width: `390px`,
  margin: `0px`,
});

const Background3: any = styled(StylesBackgroundsTransparent)(
  ({ theme }: any) => ({
    width: `390px`,
    height: `64px`,
    position: `absolute`,
    left: `0px`,
    top: `64px`,
  })
);

const Button1: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  height: `40px`,
  left: `350px`,
  top: `19px`,
});

const Icon1: any = styled('img')({
  height: `40px`,
  width: `40px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Shape: any = styled('img')({
  height: `20px`,
  width: `15.71px`,
  position: `absolute`,
  left: `12px`,
  top: `10px`,
});

const InputField: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(170, 170, 170, 1)`,
  boxSizing: `border-box`,
  borderRadius: `16px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  width: `320px`,
  height: `40px`,
  left: `16px`,
  top: `19px`,
}));

const Frame283: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  width: `358px`,
  left: `16px`,
  top: `12px`,
});

const InputType: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(13, 14, 15, 1)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `18px`,
  textTransform: `none`,
  margin: `0px`,
}));

function Chat(props: ChatProps): JSX.Element {
  return (
    <Chat1 className={props.className}>
      <Frame289474>
        <Cell>
          <Background />
          <Container>
            <Subtitle>{`Anyone got questions about this?`}</Subtitle>
            <Title>{`Sarah Ashford`}</Title>
          </Container>
          <Q20>
            <Group>
              <Vector src={VectorImage} loading="lazy" alt={'Vector'} />
              <Group1>
                <Vector1 src={Vector1Image} loading="lazy" alt={'Vector'} />
                <Vector2 src={Vector2Image} loading="lazy" alt={'Vector'} />
                <Vector3 src={Vector3Image} loading="lazy" alt={'Vector'} />
                <Vector4 src={Vector4Image} loading="lazy" alt={'Vector'} />
                <Vector5 src={Vector5Image} loading="lazy" alt={'Vector'} />
              </Group1>
              <Group2>
                <Vector6 src={Vector6Image} loading="lazy" alt={'Vector'} />
                <Vector7 src={Vector7Image} loading="lazy" alt={'Vector'} />
                <Vector8 src={Vector8Image} loading="lazy" alt={'Vector'} />
                <Vector9 src={Vector9Image} loading="lazy" alt={'Vector'} />
              </Group2>
              <Group3>
                <Vector10 src={Vector10Image} loading="lazy" alt={'Vector'} />
              </Group3>
              <Vector11 src={Vector11Image} loading="lazy" alt={'Vector'} />
              <Vector12 src={Vector12Image} loading="lazy" alt={'Vector'} />
              <Vector13 src={Vector13Image} loading="lazy" alt={'Vector'} />
              <Group4>
                <Vector14 src={Vector14Image} loading="lazy" alt={'Vector'} />
                <Vector15 src={Vector15Image} loading="lazy" alt={'Vector'} />
              </Group4>
            </Group>
          </Q20>
        </Cell>
        <Cell1>
          <Background1 />
          <Container1>
            <Subtitle1>{`Wow, awesome!`}</Subtitle1>
            <Title1>{`You`}</Title1>
          </Container1>
          <Q21>
            <Group5>
              <Vector16 src={Vector16Image} loading="lazy" alt={'Vector'} />
              <Group6>
                <Vector17 src={Vector17Image} loading="lazy" alt={'Vector'} />
                <Vector18 src={Vector18Image} loading="lazy" alt={'Vector'} />
                <Vector19 src={Vector19Image} loading="lazy" alt={'Vector'} />
                <Vector20 src={Vector20Image} loading="lazy" alt={'Vector'} />
                <Vector21 src={Vector21Image} loading="lazy" alt={'Vector'} />
              </Group6>
              <Group7>
                <Vector22 src={Vector22Image} loading="lazy" alt={'Vector'} />
              </Group7>
              <Group8>
                <Vector23 src={Vector23Image} loading="lazy" alt={'Vector'} />
                <Vector24 src={Vector24Image} loading="lazy" alt={'Vector'} />
                <Vector25 src={Vector25Image} loading="lazy" alt={'Vector'} />
              </Group8>
              <Vector26 src={Vector26Image} loading="lazy" alt={'Vector'} />
              <Vector27 src={Vector27Image} loading="lazy" alt={'Vector'} />
              <Group9>
                <Vector28 src={Vector28Image} loading="lazy" alt={'Vector'} />
                <Vector29 src={Vector29Image} loading="lazy" alt={'Vector'} />
              </Group9>
            </Group5>
          </Q21>
        </Cell1>
        <Cell2>
          <Background2 />
          <Container2>
            <Subtitle2>{`Love it! So great and helpful!`}</Subtitle2>
            <Title2>{`Paulo De Luca`}</Title2>
          </Container2>
          <Q22>
            <Group10>
              <Vector30 src={Vector30Image} loading="lazy" alt={'Vector'} />
              <Group11>
                <Vector31 src={Vector31Image} loading="lazy" alt={'Vector'} />
                <Vector32 src={Vector32Image} loading="lazy" alt={'Vector'} />
                <Vector33 src={Vector33Image} loading="lazy" alt={'Vector'} />
                <Vector34 src={Vector34Image} loading="lazy" alt={'Vector'} />
                <Vector35 src={Vector35Image} loading="lazy" alt={'Vector'} />
              </Group11>
              <Group12>
                <Vector36 src={Vector36Image} loading="lazy" alt={'Vector'} />
              </Group12>
              <Vector37 src={Vector37Image} loading="lazy" alt={'Vector'} />
              <Vector38 src={Vector38Image} loading="lazy" alt={'Vector'} />
              <Vector39 src={Vector39Image} loading="lazy" alt={'Vector'} />
              <Vector40 src={Vector40Image} loading="lazy" alt={'Vector'} />
              <Group13>
                <Vector41 src={Vector41Image} loading="lazy" alt={'Vector'} />
                <Vector42 src={Vector42Image} loading="lazy" alt={'Vector'} />
              </Group13>
            </Group10>
          </Q22>
        </Cell2>
        <Input1>
          <Background3 />
          <Button1>
            <Icon1 src={Icon1Image} loading="lazy" alt={'Icon'} />
            <Shape src={ShapeImage} loading="lazy" alt={'Shape'} />
          </Button1>
          <InputField>
            <Frame283>
              <InputType>{`Input type`}</InputType>
            </Frame283>
          </InputField>
        </Input1>
      </Frame289474>
    </Chat1>
  );
}

export default Chat;
