/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import VectorImage from 'src/assets/images/iPadPro129Landscape_Vector.png';
import Vector1Image from 'src/assets/images/iPadPro129Landscape_Vector_1.png';
import Vector2Image from 'src/assets/images/iPadPro129Landscape_Vector_2.png';
import Vector3Image from 'src/assets/images/iPadPro129Landscape_Vector_3.png';
import Vector4Image from 'src/assets/images/iPadPro129Landscape_Vector_4.png';
import Vector5Image from 'src/assets/images/iPadPro129Landscape_Vector_5.png';
import Vector6Image from 'src/assets/images/iPadPro129Landscape_Vector_6.png';
import Vector7Image from 'src/assets/images/iPadPro129Landscape_Vector_7.png';
import Vector8Image from 'src/assets/images/iPadPro129Landscape_Vector_8.png';
import Vector9Image from 'src/assets/images/iPadPro129Landscape_Vector_9.png';
import Vector10Image from 'src/assets/images/iPadPro129Landscape_Vector_10.png';
import Vector11Image from 'src/assets/images/iPadPro129Landscape_Vector_11.png';
import Vector12Image from 'src/assets/images/iPadPro129Landscape_Vector_12.png';
import Vector13Image from 'src/assets/images/iPadPro129Landscape_Vector_13.png';
import Vector14Image from 'src/assets/images/iPadPro129Landscape_Vector_14.png';
import Vector15Image from 'src/assets/images/iPadPro129Landscape_Vector_15.png';
import Vector16Image from 'src/assets/images/iPadPro129Landscape_Vector_16.png';
import Vector17Image from 'src/assets/images/iPadPro129Landscape_Vector_17.png';
import Vector18Image from 'src/assets/images/iPadPro129Landscape_Vector_18.png';
import Vector19Image from 'src/assets/images/iPadPro129Landscape_Vector_19.png';
import Vector20Image from 'src/assets/images/iPadPro129Landscape_Vector_20.png';
import Vector21Image from 'src/assets/images/iPadPro129Landscape_Vector_21.png';
import Vector22Image from 'src/assets/images/iPadPro129Landscape_Vector_22.png';
import Vector23Image from 'src/assets/images/iPadPro129Landscape_Vector_23.png';
import Vector24Image from 'src/assets/images/iPadPro129Landscape_Vector_24.png';
import Vector25Image from 'src/assets/images/iPadPro129Landscape_Vector_25.png';
import Vector26Image from 'src/assets/images/iPadPro129Landscape_Vector_26.png';
import Vector27Image from 'src/assets/images/iPadPro129Landscape_Vector_27.png';
import Search24PxImage from 'src/assets/images/iPadPro129Landscape_search_24px.svg';
import Chat24PxImage from 'src/assets/images/iPadPro129Landscape_chat_24px.svg';
import Settings24PxImage from 'src/assets/images/iPadPro129Landscape_settings_24px.svg';
import Vector28Image from 'src/assets/images/iPadPro129Landscape_Vector_28.png';
import Vector29Image from 'src/assets/images/iPadPro129Landscape_Vector_29.png';
import Vector30Image from 'src/assets/images/iPadPro129Landscape_Vector_30.png';
import Vector31Image from 'src/assets/images/iPadPro129Landscape_Vector_31.png';
import Vector32Image from 'src/assets/images/iPadPro129Landscape_Vector_32.png';
import Vector33Image from 'src/assets/images/iPadPro129Landscape_Vector_33.png';
import Vector34Image from 'src/assets/images/iPadPro129Landscape_Vector_34.png';
import Vector35Image from 'src/assets/images/iPadPro129Landscape_Vector_35.png';
import Vector36Image from 'src/assets/images/iPadPro129Landscape_Vector_36.png';
import Vector37Image from 'src/assets/images/iPadPro129Landscape_Vector_37.png';
import Vector38Image from 'src/assets/images/iPadPro129Landscape_Vector_38.png';
import Vector39Image from 'src/assets/images/iPadPro129Landscape_Vector_39.png';
import Vector40Image from 'src/assets/images/iPadPro129Landscape_Vector_40.png';
import Vector41Image from 'src/assets/images/iPadPro129Landscape_Vector_41.png';
import Vector42Image from 'src/assets/images/iPadPro129Landscape_Vector_42.png';
import Vector43Image from 'src/assets/images/iPadPro129Landscape_Vector_43.png';
import Vector44Image from 'src/assets/images/iPadPro129Landscape_Vector_44.png';
import Vector45Image from 'src/assets/images/iPadPro129Landscape_Vector_45.png';
import Vector46Image from 'src/assets/images/iPadPro129Landscape_Vector_46.png';
import Vector47Image from 'src/assets/images/iPadPro129Landscape_Vector_47.png';
import Vector48Image from 'src/assets/images/iPadPro129Landscape_Vector_48.png';
import Vector49Image from 'src/assets/images/iPadPro129Landscape_Vector_49.png';
import Vector50Image from 'src/assets/images/iPadPro129Landscape_Vector_50.png';
import Vector51Image from 'src/assets/images/iPadPro129Landscape_Vector_51.png';
import Vector52Image from 'src/assets/images/iPadPro129Landscape_Vector_52.png';
import Vector53Image from 'src/assets/images/iPadPro129Landscape_Vector_53.png';
import Vector54Image from 'src/assets/images/iPadPro129Landscape_Vector_54.png';
import Vector55Image from 'src/assets/images/iPadPro129Landscape_Vector_55.png';
import Vector56Image from 'src/assets/images/iPadPro129Landscape_Vector_56.png';
import Vector57Image from 'src/assets/images/iPadPro129Landscape_Vector_57.png';
import Vector58Image from 'src/assets/images/iPadPro129Landscape_Vector_58.png';
import Vector59Image from 'src/assets/images/iPadPro129Landscape_Vector_59.png';
import Vector60Image from 'src/assets/images/iPadPro129Landscape_Vector_60.png';
import Vector61Image from 'src/assets/images/iPadPro129Landscape_Vector_61.png';
import Vector62Image from 'src/assets/images/iPadPro129Landscape_Vector_62.png';
import Vector63Image from 'src/assets/images/iPadPro129Landscape_Vector_63.png';
import Vector64Image from 'src/assets/images/iPadPro129Landscape_Vector_64.png';
import Vector65Image from 'src/assets/images/iPadPro129Landscape_Vector_65.png';
import Vector66Image from 'src/assets/images/iPadPro129Landscape_Vector_66.png';
import Vector67Image from 'src/assets/images/iPadPro129Landscape_Vector_67.png';
import Vector68Image from 'src/assets/images/iPadPro129Landscape_Vector_68.png';
import { styled } from '@mui/material/styles';
import ControlsButtonLabel from 'src/components/ControlsButtonLabel/ControlsButtonLabel';
import Q4SubcomponentsNavig from 'src/components/Q4SubcomponentsNavig/Q4SubcomponentsNavig';
import ControlsButtonLarge from 'src/components/ControlsButtonLarge/ControlsButtonLarge';
import MagiconsGlyphArrowArrowDown2 from 'src/components/MagiconsGlyphArrowArrowDown2/MagiconsGlyphArrowArrowDown2';
import AssetsCheckboxesEmpty from 'src/components/AssetsCheckboxesEmpty/AssetsCheckboxesEmpty';
import AssetsCheckboxesOk from 'src/components/AssetsCheckboxesOk/AssetsCheckboxesOk';
import GlyphsNavToolbarAdd from 'src/components/GlyphsNavToolbarAdd/GlyphsNavToolbarAdd';
import StylesBackgroundsTransparent from 'src/components/StylesBackgroundsTransparent/StylesBackgroundsTransparent';
import ControlsButtonLargeFullWidth from 'src/components/ControlsButtonLargeFullWidth/ControlsButtonLargeFullWidth';
import { IPadPro129LandscapeProps } from 'src/types';

const IPadPro129Landscape1: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1024px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const MainPanel: any = styled('div')({
  background: `linear-gradient(105.3deg, rgba(153, 153, 153, 1) 2.9563745960448617%, rgba(232, 232, 232, 1) 93.86177888289811%)`,
  borderRadius: `0px`,
  width: `1440px`,
  height: `960px`,
  position: `absolute`,
  left: `0px`,
  top: `64px`,
});

const MinimizedSidebarNav: any = styled('div')({
  opacity: `0.4000000059604645`,
  backgroundColor: `rgba(0, 0, 0, 1)`,
  borderRadius: `0px`,
  width: `80px`,
  height: `960px`,
  position: `absolute`,
  left: `0px`,
  top: `64px`,
});

const TopHeaderNav: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1440px`,
  height: `64px`,
  left: `0px`,
  top: `0px`,
});

const TopMenuBar: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(181, 173, 173, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `13px 20px`,
  boxSizing: `border-box`,
  width: `1440px`,
  height: `37px`,
  left: `0px`,
  top: `63px`,
});

const Label: any = styled(ControlsButtonLabel)(({ theme }: any) => ({
  margin: `0px`,
}));

const Label1: any = styled(ControlsButtonLabel)(({ theme }: any) => ({
  margin: `0px`,
}));

const Label2: any = styled(ControlsButtonLabel)(({ theme }: any) => ({
  margin: `0px`,
}));

const TopBar: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1440px`,
  height: `60px`,
  left: `0px`,
  top: `0px`,
});

const Rectangle4126: any = styled('div')({
  backgroundColor: `rgba(48, 48, 48, 1)`,
  borderRadius: `8px 8px 0px 0px`,
  width: `1440px`,
  height: `60px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Q2Icons: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `1259px`,
  top: `18px`,
});

const Q4SubcomponentsNavig1: any = styled(Q4SubcomponentsNavig)(
  ({ theme }: any) => ({
    margin: `0px`,
  })
);

const Q4SubcomponentsNavig2: any = styled(Q4SubcomponentsNavig)(
  ({ theme }: any) => ({
    margin: `0px 0px 0px 16px`,
  })
);

const Profile: any = styled('div')({
  borderRadius: `200px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `24px`,
  height: `24px`,
  left: `1396px`,
  top: `18px`,
  overflow: `hidden`,
});

const Group: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `25.24px`,
  height: `31.13px`,
  left: `-1px`,
  top: `0px`,
});

const Vector: any = styled('img')({
  height: `24px`,
  width: `24px`,
  position: `absolute`,
  left: `1px`,
  top: `0px`,
});

const Group1: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `12.39px`,
  height: `20.63px`,
  left: `6px`,
  top: `5px`,
});

const Vector1: any = styled('img')({
  height: `3.75px`,
  width: `3.75px`,
  position: `absolute`,
  left: `0px`,
  top: `7px`,
});

const Vector2: any = styled('img')({
  height: `10.13px`,
  width: `6.38px`,
  position: `absolute`,
  left: `2px`,
  top: `11px`,
});

const Vector3: any = styled('img')({
  height: `8.03px`,
  width: `6.07px`,
  position: `absolute`,
  left: `2px`,
  top: `9px`,
});

const Vector4: any = styled('img')({
  height: `16.31px`,
  width: `11.13px`,
  position: `absolute`,
  left: `1px`,
  top: `0px`,
});

const Vector5: any = styled('img')({
  height: `0.75px`,
  width: `1.13px`,
  position: `absolute`,
  left: `9px`,
  top: `11px`,
});

const Group2: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `15px`,
  height: `8.63px`,
  left: `4px`,
  top: `23px`,
});

const Vector6: any = styled('img')({
  height: `8.63px`,
  width: `15px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group3: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `19.99px`,
  height: `16.21px`,
  left: `0px`,
  top: `3px`,
});

const Vector7: any = styled('img')({
  height: `13.76px`,
  width: `6.12px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector8: any = styled('img')({
  height: `3.99px`,
  width: `3.52px`,
  position: `absolute`,
  left: `5px`,
  top: `2px`,
});

const Vector9: any = styled('img')({
  height: `15.86px`,
  width: `15px`,
  position: `absolute`,
  left: `5px`,
  top: `0px`,
});

const Vector10: any = styled('img')({
  height: `1.5px`,
  width: `1.13px`,
  position: `absolute`,
  left: `12px`,
  top: `14px`,
});

const Vector11: any = styled('img')({
  height: `1.5px`,
  width: `1.13px`,
  position: `absolute`,
  left: `16px`,
  top: `14px`,
});

const Group4: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `8.63px`,
  height: `1.13px`,
  left: `10px`,
  top: `15px`,
});

const Vector12: any = styled('img')({
  height: `1.13px`,
  width: `1.88px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector13: any = styled('img')({
  height: `1.13px`,
  width: `1.5px`,
  position: `absolute`,
  left: `7px`,
  top: `0px`,
});

const TopNavBarBorder: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1440px`,
  height: `4px`,
  left: `0px`,
  top: `60px`,
});

const ControlsButtonLarge1: any = styled(ControlsButtonLarge)(
  ({ theme }: any) => ({
    width: `1440px`,
    height: `4px`,
    position: `absolute`,
    left: `0px`,
    top: `0px`,
  })
);

const QuickActions: any = styled('div')({
  backdropFilter: `blur(200px)`,
  WebkitBackdropFilter: `blur(200px)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `60px 24px`,
  boxSizing: `border-box`,
  width: `80px`,
  height: `961px`,
  left: `0px`,
  top: `63px`,
});

const Q19: any = styled('div')({
  borderRadius: `200px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `34px`,
  width: `34px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Group5: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `35.76px`,
  height: `44.09px`,
  left: `-2px`,
  top: `0px`,
});

const Vector14: any = styled('img')({
  height: `34px`,
  width: `34px`,
  position: `absolute`,
  left: `2px`,
  top: `0px`,
});

const Group6: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `17.55px`,
  height: `29.22px`,
  left: `9px`,
  top: `7px`,
});

const Vector15: any = styled('img')({
  height: `5.31px`,
  width: `5.31px`,
  position: `absolute`,
  left: `0px`,
  top: `10px`,
});

const Vector16: any = styled('img')({
  height: `14.34px`,
  width: `9.03px`,
  position: `absolute`,
  left: `3px`,
  top: `15px`,
});

const Vector17: any = styled('img')({
  height: `11.37px`,
  width: `8.6px`,
  position: `absolute`,
  left: `3px`,
  top: `13px`,
});

const Vector18: any = styled('img')({
  height: `23.11px`,
  width: `15.77px`,
  position: `absolute`,
  left: `2px`,
  top: `0px`,
});

const Vector19: any = styled('img')({
  height: `1.06px`,
  width: `1.59px`,
  position: `absolute`,
  left: `12px`,
  top: `15px`,
});

const Group7: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `21.25px`,
  height: `12.22px`,
  left: `5px`,
  top: `32px`,
});

const Vector20: any = styled('img')({
  height: `12.22px`,
  width: `21.25px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group8: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `28.32px`,
  height: `22.96px`,
  left: `0px`,
  top: `4px`,
});

const Vector21: any = styled('img')({
  height: `19.49px`,
  width: `8.67px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector22: any = styled('img')({
  height: `5.65px`,
  width: `4.98px`,
  position: `absolute`,
  left: `7px`,
  top: `3px`,
});

const Vector23: any = styled('img')({
  height: `22.47px`,
  width: `21.25px`,
  position: `absolute`,
  left: `7px`,
  top: `0px`,
});

const Vector24: any = styled('img')({
  height: `2.13px`,
  width: `1.59px`,
  position: `absolute`,
  left: `18px`,
  top: `19px`,
});

const Vector25: any = styled('img')({
  height: `2.13px`,
  width: `1.59px`,
  position: `absolute`,
  left: `23px`,
  top: `19px`,
});

const Group9: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `12.22px`,
  height: `1.59px`,
  left: `15px`,
  top: `21px`,
});

const Vector26: any = styled('img')({
  height: `1.59px`,
  width: `2.66px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector27: any = styled('img')({
  height: `1.59px`,
  width: `2.13px`,
  position: `absolute`,
  left: `10px`,
  top: `0px`,
});

const Search24Px: any = styled('img')({
  height: `auto`,
  width: `34px`,
  margin: `60px 0px 0px 0px`,
});

const Chat24Px: any = styled('img')({
  height: `auto`,
  width: `34px`,
  margin: `60px 0px 0px 0px`,
});

const Settings24Px: any = styled('img')({
  height: `auto`,
  width: `34px`,
  margin: `60px 0px 0px 0px`,
});

const InviteMemberParking: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `510px`,
  height: `673px`,
  left: `465px`,
  top: `208px`,
});

const DropdownPanel: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `40px 60px`,
  boxSizing: `border-box`,
  left: `0px`,
  top: `57px`,
  overflow: `hidden`,
});

const BudgetDropdown: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `390px`,
  margin: `0px`,
});

const BudgetDropdown1: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `24px 12px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const InputField: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(170, 170, 170, 1)`,
  boxSizing: `border-box`,
  borderRadius: `16px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `12px 16px`,
  width: `390px`,
  margin: `0px`,
}));

const Frame283: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Grocery: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(13, 14, 15, 1)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `18px`,
  textTransform: `none`,
  margin: `0px`,
}));

const MagiconsGlyphArrowAr: any = styled(MagiconsGlyphArrowArrowDown2)(
  ({ theme }: any) => ({
    width: `32px`,
    height: `32px`,
    margin: `0px`,
  })
);

const ProfileListItemFalse: any = styled('div')(({ theme }: any) => ({
  backgroundColor: theme.palette['Primary']['Contrast'],
  boxShadow: `inset 0px -1px 0px rgba(224, 224, 224, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `12px`,
  boxSizing: `border-box`,
  width: `390px`,
  margin: `0px`,
}));

const LeftSide: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 12px 0px 0px`,
  boxSizing: `border-box`,
  width: `366px`,
  margin: `0px`,
});

const Q18: any = styled('div')({
  borderRadius: `200px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  height: `40px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Group10: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  height: `51.88px`,
  left: `0px`,
  top: `0px`,
});

const Vector28: any = styled('img')({
  height: `40px`,
  width: `40px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group11: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `20.65px`,
  height: `34.38px`,
  left: `8px`,
  top: `8px`,
});

const Vector29: any = styled('img')({
  height: `6.25px`,
  width: `6.25px`,
  position: `absolute`,
  left: `0px`,
  top: `12px`,
});

const Vector30: any = styled('img')({
  height: `16.88px`,
  width: `10.63px`,
  position: `absolute`,
  left: `3px`,
  top: `18px`,
});

const Vector31: any = styled('img')({
  height: `12.5px`,
  width: `9.37px`,
  position: `absolute`,
  left: `4px`,
  top: `16px`,
});

const Vector32: any = styled('img')({
  height: `26.87px`,
  width: `18.55px`,
  position: `absolute`,
  left: `2px`,
  top: `0px`,
});

const Vector33: any = styled('img')({
  height: `1.25px`,
  width: `1.88px`,
  position: `absolute`,
  left: `14px`,
  top: `18px`,
});

const Group12: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `25px`,
  height: `16.25px`,
  left: `4px`,
  top: `36px`,
});

const Vector34: any = styled('img')({
  height: `14.38px`,
  width: `25px`,
  position: `absolute`,
  left: `0px`,
  top: `2px`,
});

const Vector35: any = styled('img')({
  height: `2.5px`,
  width: `11.88px`,
  position: `absolute`,
  left: `6px`,
  top: `1px`,
});

const Vector36: any = styled('img')({
  height: `2.19px`,
  width: `11.88px`,
  position: `absolute`,
  left: `6px`,
  top: `1px`,
});

const Vector37: any = styled('img')({
  height: `1.88px`,
  width: `12.5px`,
  position: `absolute`,
  left: `6px`,
  top: `0px`,
});

const Group13: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `22.5px`,
  height: `36.25px`,
  left: `8px`,
  top: `4px`,
});

const Vector38: any = styled('img')({
  height: `36.25px`,
  width: `22.5px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector39: any = styled('img')({
  height: `3.75px`,
  width: `6.96px`,
  position: `absolute`,
  left: `18px`,
  top: `28px`,
});

const Vector40: any = styled('img')({
  height: `3.15px`,
  width: `5.04px`,
  position: `absolute`,
  left: `18px`,
  top: `29px`,
});

const Vector41: any = styled('img')({
  height: `1.25px`,
  width: `6.25px`,
  position: `absolute`,
  left: `19px`,
  top: `28px`,
});

const Group14: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `8.13px`,
  height: `2.5px`,
  left: `19px`,
  top: `23px`,
});

const Vector42: any = styled('img')({
  height: `2.5px`,
  width: `1.88px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector43: any = styled('img')({
  height: `2.5px`,
  width: `1.88px`,
  position: `absolute`,
  left: `6px`,
  top: `0px`,
});

const Text: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `264px`,
  margin: `0px 0px 0px 12px`,
});

const Frame1: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `185px`,
  margin: `0px`,
});

const SarahAshford: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: theme.palette['Text']['Primary'],
  fontStyle: `normal`,
  fontFamily: `SF Pro Text`,
  fontWeight: `400`,
  fontSize: `17px`,
  letterSpacing: `-0.4099999964237213px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  flex: `1`,
  margin: `0px`,
}));

const EllenchoQuestAi: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: theme.palette['Text']['Secondary'],
  fontStyle: `normal`,
  fontFamily: `SF Pro Text`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `110.00000238418579%`,
  textTransform: `none`,
  width: `185px`,
  margin: `2px 0px 0px 0px`,
}));

const Action: any = styled(AssetsCheckboxesEmpty)(({ theme }: any) => ({
  width: `30px`,
  height: `30px`,
  margin: `0px 0px 0px 12px`,
}));

const ProfileListItemFalse1: any = styled('div')(({ theme }: any) => ({
  backgroundColor: theme.palette['Primary']['Contrast'],
  boxShadow: `inset 0px -1px 0px rgba(224, 224, 224, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `12px`,
  boxSizing: `border-box`,
  width: `390px`,
  margin: `0px`,
}));

const LeftSide1: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 12px 0px 0px`,
  boxSizing: `border-box`,
  width: `366px`,
  margin: `0px`,
});

const Q20: any = styled('div')({
  borderRadius: `200px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  height: `40px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Group15: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  height: `51.88px`,
  left: `0px`,
  top: `0px`,
});

const Vector44: any = styled('img')({
  height: `40px`,
  width: `40px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group16: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `20.65px`,
  height: `34.38px`,
  left: `8px`,
  top: `8px`,
});

const Vector45: any = styled('img')({
  height: `6.25px`,
  width: `6.25px`,
  position: `absolute`,
  left: `0px`,
  top: `12px`,
});

const Vector46: any = styled('img')({
  height: `16.88px`,
  width: `10.63px`,
  position: `absolute`,
  left: `3px`,
  top: `18px`,
});

const Vector47: any = styled('img')({
  height: `12.5px`,
  width: `9.37px`,
  position: `absolute`,
  left: `4px`,
  top: `16px`,
});

const Vector48: any = styled('img')({
  height: `26.87px`,
  width: `18.55px`,
  position: `absolute`,
  left: `2px`,
  top: `0px`,
});

const Vector49: any = styled('img')({
  height: `1.25px`,
  width: `1.88px`,
  position: `absolute`,
  left: `14px`,
  top: `18px`,
});

const Group17: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `25px`,
  height: `14.38px`,
  left: `4px`,
  top: `38px`,
});

const Vector50: any = styled('img')({
  height: `14.38px`,
  width: `25px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector51: any = styled('img')({
  height: `19.84px`,
  width: `25.03px`,
  position: `absolute`,
  left: `7px`,
  top: `3px`,
});

const Vector52: any = styled('img')({
  height: `3.75px`,
  width: `6.96px`,
  position: `absolute`,
  left: `18px`,
  top: `28px`,
});

const Vector53: any = styled('img')({
  height: `3.15px`,
  width: `5.04px`,
  position: `absolute`,
  left: `18px`,
  top: `29px`,
});

const Vector54: any = styled('img')({
  height: `1.25px`,
  width: `6.25px`,
  position: `absolute`,
  left: `19px`,
  top: `28px`,
});

const Group18: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `8.13px`,
  height: `2.5px`,
  left: `19px`,
  top: `23px`,
});

const Vector55: any = styled('img')({
  height: `2.5px`,
  width: `1.88px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector56: any = styled('img')({
  height: `2.5px`,
  width: `1.88px`,
  position: `absolute`,
  left: `6px`,
  top: `0px`,
});

const Text1: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `264px`,
  margin: `0px 0px 0px 12px`,
});

const Frame11: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `185px`,
  margin: `0px`,
});

const PauloDeLuca: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: theme.palette['Text']['Primary'],
  fontStyle: `normal`,
  fontFamily: `SF Pro Text`,
  fontWeight: `400`,
  fontSize: `17px`,
  letterSpacing: `-0.4099999964237213px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  flex: `1`,
  margin: `0px`,
}));

const EllenchoQuestAi1: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: theme.palette['Text']['Secondary'],
  fontStyle: `normal`,
  fontFamily: `SF Pro Text`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `110.00000238418579%`,
  textTransform: `none`,
  width: `185px`,
  margin: `2px 0px 0px 0px`,
}));

const Action1: any = styled(AssetsCheckboxesEmpty)(({ theme }: any) => ({
  width: `30px`,
  height: `30px`,
  margin: `0px 0px 0px 12px`,
}));

const ProfileListItemFalse2: any = styled('div')(({ theme }: any) => ({
  backgroundColor: theme.palette['Primary']['Contrast'],
  boxShadow: `inset 0px -1px 0px rgba(224, 224, 224, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `12px`,
  boxSizing: `border-box`,
  width: `390px`,
  margin: `0px`,
}));

const LeftSide2: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 12px 0px 0px`,
  boxSizing: `border-box`,
  width: `366px`,
  margin: `0px`,
});

const Q21: any = styled('div')({
  borderRadius: `200px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  height: `40px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Group19: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  height: `51.88px`,
  left: `0px`,
  top: `0px`,
});

const Vector57: any = styled('img')({
  height: `40px`,
  width: `40px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group20: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `20.65px`,
  height: `34.38px`,
  left: `8px`,
  top: `8px`,
});

const Vector58: any = styled('img')({
  height: `6.25px`,
  width: `6.25px`,
  position: `absolute`,
  left: `0px`,
  top: `12px`,
});

const Vector59: any = styled('img')({
  height: `16.88px`,
  width: `10.63px`,
  position: `absolute`,
  left: `3px`,
  top: `18px`,
});

const Vector60: any = styled('img')({
  height: `12.5px`,
  width: `9.37px`,
  position: `absolute`,
  left: `4px`,
  top: `16px`,
});

const Vector61: any = styled('img')({
  height: `26.87px`,
  width: `18.55px`,
  position: `absolute`,
  left: `2px`,
  top: `0px`,
});

const Vector62: any = styled('img')({
  height: `1.25px`,
  width: `1.88px`,
  position: `absolute`,
  left: `14px`,
  top: `18px`,
});

const Group21: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `25px`,
  height: `14.38px`,
  left: `4px`,
  top: `38px`,
});

const Vector63: any = styled('img')({
  height: `14.38px`,
  width: `25px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector64: any = styled('img')({
  height: `17.4px`,
  width: `24.67px`,
  position: `absolute`,
  left: `7px`,
  top: `5px`,
});

const Vector65: any = styled('img')({
  height: `5.34px`,
  width: `5.34px`,
  position: `absolute`,
  left: `16px`,
  top: `20px`,
});

const Vector66: any = styled('img')({
  height: `5.34px`,
  width: `5.34px`,
  position: `absolute`,
  left: `25px`,
  top: `20px`,
});

const Vector67: any = styled('img')({
  height: `0.06px`,
  width: `4.38px`,
  position: `absolute`,
  left: `21px`,
  top: `22px`,
});

const Group22: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `9.38px`,
  height: `1.88px`,
  left: `18px`,
  top: `27px`,
});

const Vector68: any = styled('img')({
  height: `1.88px`,
  width: `9.38px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Text2: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `264px`,
  margin: `0px 0px 0px 12px`,
});

const Frame12: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `185px`,
  margin: `0px`,
});

const MannySalazar: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: theme.palette['Text']['Primary'],
  fontStyle: `normal`,
  fontFamily: `SF Pro Text`,
  fontWeight: `400`,
  fontSize: `17px`,
  letterSpacing: `-0.4099999964237213px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  flex: `1`,
  margin: `0px`,
}));

const MannyEmailCom: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: theme.palette['Text']['Secondary'],
  fontStyle: `normal`,
  fontFamily: `SF Pro Text`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `110.00000238418579%`,
  textTransform: `none`,
  width: `185px`,
  margin: `2px 0px 0px 0px`,
}));

const Action11: any = styled(AssetsCheckboxesOk)(({ theme }: any) => ({
  width: `30px`,
  height: `30px`,
  margin: `0px 0px 0px 12px`,
}));

const ProfileListItemFalse3: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `inset 0px -1px 0px rgba(224, 224, 224, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `12px`,
  boxSizing: `border-box`,
  width: `390px`,
  margin: `0px`,
});

const LeftSide3: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 12px 0px 0px`,
  boxSizing: `border-box`,
  width: `366px`,
  margin: `0px`,
});

const Oval: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  height: `40px`,
  margin: `0px`,
});

const Oval1: any = styled('div')({
  border: `2px solid rgba(0, 0, 0, 0.5)`,
  borderRadius: `1000px`,
  width: `40px`,
  height: `40px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const AssetsGlyphsAdd: any = styled(GlyphsNavToolbarAdd)(({ theme }: any) => ({
  width: `29.47px`,
  height: `29.47px`,
  position: `absolute`,
  left: `5px`,
  top: `5px`,
}));

const Text3: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `264px`,
  margin: `0px 0px 0px 12px`,
});

const Frame13: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `185px`,
  margin: `0px`,
});

const InviteWithEmail: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: theme.palette['Text']['Primary'],
  fontStyle: `normal`,
  fontFamily: `SF Pro Text`,
  fontWeight: `400`,
  fontSize: `17px`,
  letterSpacing: `-0.4099999964237213px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  flex: `1`,
  margin: `0px`,
}));

const Action2: any = styled(AssetsCheckboxesEmpty)(({ theme }: any) => ({
  width: `30px`,
  height: `30px`,
  margin: `0px 0px 0px 12px`,
}));

const Frame14392: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `24px 0px`,
  boxSizing: `border-box`,
  left: `60px`,
  top: `500px`,
});

const Button1: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `60px`,
  width: `390px`,
  margin: `0px`,
});

const Background: any = styled(StylesBackgroundsTransparent)(
  ({ theme }: any) => ({
    width: `390px`,
    height: `60px`,
    position: `absolute`,
    left: `0px`,
    top: `0px`,
  })
);

const Button2: any = styled(ControlsButtonLargeFullWidth)(({ theme }: any) => ({
  width: `356.72px`,
  height: `51.72px`,
  position: `absolute`,
  left: `17px`,
  top: `4px`,
}));

const Button3: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `60px`,
  width: `390px`,
  margin: `5px 0px 0px 0px`,
});

const Background1: any = styled(StylesBackgroundsTransparent)(
  ({ theme }: any) => ({
    width: `390px`,
    height: `60px`,
    position: `absolute`,
    left: `0px`,
    top: `0px`,
  })
);

const Button4: any = styled(ControlsButtonLargeFullWidth)(({ theme }: any) => ({
  width: `356.72px`,
  height: `51.72px`,
  position: `absolute`,
  left: `17px`,
  top: `4px`,
}));

function IPadPro129Landscape(props: IPadPro129LandscapeProps): JSX.Element {
  return (
    <IPadPro129Landscape1 className={props.className}>
      <MainPanel></MainPanel>
      {false && <MinimizedSidebarNav></MinimizedSidebarNav>}
      <TopHeaderNav>
        {false && (
          <TopMenuBar>
            <Label />
            <Label1 />
            <Label2 />
          </TopMenuBar>
        )}
        <TopBar>
          <Rectangle4126></Rectangle4126>
          <Q2Icons>
            <Q4SubcomponentsNavig1 />
            <Q4SubcomponentsNavig2 />
          </Q2Icons>
          {false && (
            <Profile>
              <Group>
                <Vector src={VectorImage} loading="lazy" alt={'Vector'} />
                <Group1>
                  <Vector1 src={Vector1Image} loading="lazy" alt={'Vector'} />
                  <Vector2 src={Vector2Image} loading="lazy" alt={'Vector'} />
                  <Vector3 src={Vector3Image} loading="lazy" alt={'Vector'} />
                  <Vector4 src={Vector4Image} loading="lazy" alt={'Vector'} />
                  <Vector5 src={Vector5Image} loading="lazy" alt={'Vector'} />
                </Group1>
                <Group2>
                  <Vector6 src={Vector6Image} loading="lazy" alt={'Vector'} />
                </Group2>
                <Group3>
                  <Vector7 src={Vector7Image} loading="lazy" alt={'Vector'} />
                  <Vector8 src={Vector8Image} loading="lazy" alt={'Vector'} />
                  <Vector9 src={Vector9Image} loading="lazy" alt={'Vector'} />
                </Group3>
                <Vector10 src={Vector10Image} loading="lazy" alt={'Vector'} />
                <Vector11 src={Vector11Image} loading="lazy" alt={'Vector'} />
                <Group4>
                  <Vector12 src={Vector12Image} loading="lazy" alt={'Vector'} />
                  <Vector13 src={Vector13Image} loading="lazy" alt={'Vector'} />
                </Group4>
              </Group>
            </Profile>
          )}
        </TopBar>
        <TopNavBarBorder>
          <ControlsButtonLarge1 />
        </TopNavBarBorder>
      </TopHeaderNav>
      <QuickActions>
        <Q19>
          <Group5>
            <Vector14 src={Vector14Image} loading="lazy" alt={'Vector'} />
            <Group6>
              <Vector15 src={Vector15Image} loading="lazy" alt={'Vector'} />
              <Vector16 src={Vector16Image} loading="lazy" alt={'Vector'} />
              <Vector17 src={Vector17Image} loading="lazy" alt={'Vector'} />
              <Vector18 src={Vector18Image} loading="lazy" alt={'Vector'} />
              <Vector19 src={Vector19Image} loading="lazy" alt={'Vector'} />
            </Group6>
            <Group7>
              <Vector20 src={Vector20Image} loading="lazy" alt={'Vector'} />
            </Group7>
            <Group8>
              <Vector21 src={Vector21Image} loading="lazy" alt={'Vector'} />
              <Vector22 src={Vector22Image} loading="lazy" alt={'Vector'} />
              <Vector23 src={Vector23Image} loading="lazy" alt={'Vector'} />
            </Group8>
            <Vector24 src={Vector24Image} loading="lazy" alt={'Vector'} />
            <Vector25 src={Vector25Image} loading="lazy" alt={'Vector'} />
            <Group9>
              <Vector26 src={Vector26Image} loading="lazy" alt={'Vector'} />
              <Vector27 src={Vector27Image} loading="lazy" alt={'Vector'} />
            </Group9>
          </Group5>
        </Q19>
        <Search24Px src={Search24PxImage} loading="lazy" alt={'search_24px'} />
        <Chat24Px src={Chat24PxImage} loading="lazy" alt={'chat_24px'} />
        <Settings24Px
          src={Settings24PxImage}
          loading="lazy"
          alt={'settings_24px'}
        />
      </QuickActions>
      <InviteMemberParking>
        <DropdownPanel>
          <BudgetDropdown>
            <BudgetDropdown1>
              <InputField>
                <Frame283>
                  <Grocery>{`Grocery`}</Grocery>
                  <MagiconsGlyphArrowAr />
                </Frame283>
              </InputField>
            </BudgetDropdown1>
          </BudgetDropdown>
          <ProfileListItemFalse>
            <LeftSide>
              <Q18>
                <Group10>
                  <Vector28 src={Vector28Image} loading="lazy" alt={'Vector'} />
                  <Group11>
                    <Vector29
                      src={Vector29Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                    <Vector30
                      src={Vector30Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                    <Vector31
                      src={Vector31Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                    <Vector32
                      src={Vector32Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                    <Vector33
                      src={Vector33Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                  </Group11>
                  <Group12>
                    <Vector34
                      src={Vector34Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                    <Vector35
                      src={Vector35Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                    <Vector36
                      src={Vector36Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                    <Vector37
                      src={Vector37Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                  </Group12>
                  <Group13>
                    <Vector38
                      src={Vector38Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                  </Group13>
                  <Vector39 src={Vector39Image} loading="lazy" alt={'Vector'} />
                  <Vector40 src={Vector40Image} loading="lazy" alt={'Vector'} />
                  <Vector41 src={Vector41Image} loading="lazy" alt={'Vector'} />
                  <Group14>
                    <Vector42
                      src={Vector42Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                    <Vector43
                      src={Vector43Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                  </Group14>
                </Group10>
              </Q18>
              <Text>
                <Frame1>
                  <SarahAshford>{`Sarah Ashford`}</SarahAshford>
                </Frame1>
                <EllenchoQuestAi>{`sarah@email.com`}</EllenchoQuestAi>
              </Text>
              <Action />
            </LeftSide>
          </ProfileListItemFalse>
          <ProfileListItemFalse1>
            <LeftSide1>
              <Q20>
                <Group15>
                  <Vector44 src={Vector44Image} loading="lazy" alt={'Vector'} />
                  <Group16>
                    <Vector45
                      src={Vector45Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                    <Vector46
                      src={Vector46Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                    <Vector47
                      src={Vector47Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                    <Vector48
                      src={Vector48Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                    <Vector49
                      src={Vector49Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                  </Group16>
                  <Group17>
                    <Vector50
                      src={Vector50Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                  </Group17>
                  <Vector51 src={Vector51Image} loading="lazy" alt={'Vector'} />
                  <Vector52 src={Vector52Image} loading="lazy" alt={'Vector'} />
                  <Vector53 src={Vector53Image} loading="lazy" alt={'Vector'} />
                  <Vector54 src={Vector54Image} loading="lazy" alt={'Vector'} />
                  <Group18>
                    <Vector55
                      src={Vector55Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                    <Vector56
                      src={Vector56Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                  </Group18>
                </Group15>
              </Q20>
              <Text1>
                <Frame11>
                  <PauloDeLuca>{`Paulo De Luca`}</PauloDeLuca>
                </Frame11>
                <EllenchoQuestAi1>{`paulo@email.com`}</EllenchoQuestAi1>
              </Text1>
              <Action1 />
            </LeftSide1>
          </ProfileListItemFalse1>
          <ProfileListItemFalse2>
            <LeftSide2>
              <Q21>
                <Group19>
                  <Vector57 src={Vector57Image} loading="lazy" alt={'Vector'} />
                  <Group20>
                    <Vector58
                      src={Vector58Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                    <Vector59
                      src={Vector59Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                    <Vector60
                      src={Vector60Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                    <Vector61
                      src={Vector61Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                    <Vector62
                      src={Vector62Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                  </Group20>
                  <Group21>
                    <Vector63
                      src={Vector63Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                  </Group21>
                  <Vector64 src={Vector64Image} loading="lazy" alt={'Vector'} />
                  <Vector65 src={Vector65Image} loading="lazy" alt={'Vector'} />
                  <Vector66 src={Vector66Image} loading="lazy" alt={'Vector'} />
                  <Vector67 src={Vector67Image} loading="lazy" alt={'Vector'} />
                  <Group22>
                    <Vector68
                      src={Vector68Image}
                      loading="lazy"
                      alt={'Vector'}
                    />
                  </Group22>
                </Group19>
              </Q21>
              <Text2>
                <Frame12>
                  <MannySalazar>{`Manny Salazar`}</MannySalazar>
                </Frame12>
                <MannyEmailCom>{`manny@email.com`}</MannyEmailCom>
              </Text2>
              <Action11 />
            </LeftSide2>
          </ProfileListItemFalse2>
          <ProfileListItemFalse3>
            <LeftSide3>
              <Oval>
                <Oval1></Oval1>
                <AssetsGlyphsAdd />
              </Oval>
              <Text3>
                <Frame13>
                  <InviteWithEmail>{`Invite with email`}</InviteWithEmail>
                </Frame13>
              </Text3>
              <Action2 />
            </LeftSide3>
          </ProfileListItemFalse3>
        </DropdownPanel>
        <Frame14392>
          <Button1>
            <Background />
            <Button2 />
          </Button1>
          <Button3>
            <Background1 />
            <Button4 />
          </Button3>
        </Frame14392>
      </InviteMemberParking>
    </IPadPro129Landscape1>
  );
}

export default IPadPro129Landscape;
