/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Group289387Image from 'src/assets/images/MainPanelThreadsAllBudgets_Group_289387.png';
import InformationIconImage from 'src/assets/images/MainPanelThreadsAllBudgets_Information_Icon.png';
import Icon2Image from 'src/assets/images/MainPanelThreadsAllBudgets_Icon.png';
import { styled } from '@mui/material/styles';
import MembersAdd from 'src/components/MembersAdd/MembersAdd';
import { MainPanelThreadsAllBProps } from 'src/types';

const MainPanelThreadsAllB1: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: `653.11px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `60px`,
  boxSizing: `border-box`,
  width: 'fit-content',
});

const Group289454: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `30px`,
  width: `580px`,
  margin: `0px`,
});

const AiCoach: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `580px`,
  height: `30px`,
  left: `0px`,
  top: `0px`,
});

const Group289373: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `580px`,
  height: `30px`,
  left: `0px`,
  top: `0px`,
});

const ChatGptFlyout: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `580px`,
  height: `30px`,
  left: `0px`,
  top: `0px`,
});

const Rectangle4125: any = styled('div')({
  borderRadius: `0px`,
  width: `580px`,
  height: `30px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group289416: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `64px`,
  height: `30px`,
  left: `30px`,
  top: `0px`,
});

const Group289391: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `64px`,
  height: `30px`,
  left: `0px`,
  top: `0px`,
});

const Group289369: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `64px`,
  height: `30px`,
  left: `0px`,
  top: `0px`,
});

const Text: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 0.8)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `-0.5px`,
  textDecoration: `none`,
  lineHeight: `120.00000476837158%`,
  textTransform: `none`,
  width: `64px`,
  height: `30px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group289387: any = styled('img')({
  height: `30px`,
  width: `30px`,
  position: `absolute`,
  left: `30px`,
  top: `30px`,
});

const Cell: any = styled('div')({
  backdropFilter: `blur(48.59000015258789px)`,
  WebkitBackdropFilter: `blur(48.59000015258789px)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `160px`,
  width: `580px`,
  margin: `12px 0px 0px 0px`,
});

const Background: any = styled('div')({
  backgroundColor: `rgba(251, 251, 251, 1)`,
  border: `1px solid rgba(190, 190, 190, 1)`,
  borderRadius: `0px`,
  width: `580px`,
  height: `160px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame14386: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `556px`,
  left: `12px`,
  top: `17px`,
});

const Icon1: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  height: `40px`,
  margin: `0px`,
});

const Bitmap: any = styled('div')({
  backgroundColor: `rgba(118, 118, 118, 1)`,
  borderRadius: `100px`,
  width: `40px`,
  height: `40px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group289467: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `386px`,
  height: `40px`,
  margin: `0px 0px 0px 15px`,
});

const Title: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `600`,
  fontSize: `20px`,
  letterSpacing: `-0.4099999964237213px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  opacity: `0.800000011920929`,
  width: `352.94px`,
  height: `20.51px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Text1: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 0.5)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `-0.20999999344348907px`,
  textDecoration: `none`,
  lineHeight: `120.00000476837158%`,
  textTransform: `none`,
  width: `386px`,
  position: `absolute`,
  left: `0px`,
  top: `17px`,
});

const MembersAdd1: any = styled(MembersAdd)(({ theme }: any) => ({
  width: `100px`,
  position: `absolute`,
  left: `456px`,
  top: `0px`,
}));

const Frame14379: any = styled('div')({
  opacity: `0.800000011920929`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `8px 0px`,
  boxSizing: `border-box`,
  left: `0px`,
  top: `59px`,
});

const Frame14378: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Group289430: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `38px`,
  width: `580px`,
  margin: `0px`,
});

const Frame89: any = styled('div')({
  borderRadius: `10px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-end`,
  padding: `5px 10px`,
  boxSizing: `border-box`,
  width: `72.63px`,
  left: `0px`,
  top: `0px`,
});

const Aug9: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `-0.5px`,
  textDecoration: `none`,
  lineHeight: `28px`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame14376: any = styled('div')({
  borderRadius: `10px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-end`,
  alignItems: `center`,
  padding: `5px 15px 5px 10px`,
  boxSizing: `border-box`,
  width: `150px`,
  left: `430px`,
  top: `0px`,
});

const Q25792: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `-0.5px`,
  textDecoration: `none`,
  lineHeight: `28px`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame14375: any = styled('div')({
  borderRadius: `10px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `5px 10px`,
  boxSizing: `border-box`,
  width: `357px`,
  left: `73px`,
  top: `0px`,
});

const WholeFoodsMarket: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `-0.5px`,
  textDecoration: `none`,
  lineHeight: `28px`,
  textTransform: `none`,
  margin: `0px`,
});

const Group2894301: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `38px`,
  width: `580px`,
  margin: `8px 0px 0px 0px`,
});

const Frame891: any = styled('div')({
  borderRadius: `10px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-end`,
  padding: `5px 10px`,
  boxSizing: `border-box`,
  width: `72.63px`,
  left: `0px`,
  top: `0px`,
});

const Aug3: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `-0.5px`,
  textDecoration: `none`,
  lineHeight: `28px`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame143761: any = styled('div')({
  borderRadius: `10px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-end`,
  alignItems: `center`,
  padding: `5px 15px 5px 10px`,
  boxSizing: `border-box`,
  width: `150px`,
  left: `430px`,
  top: `0px`,
});

const Checkbox1: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `24px`,
  height: `24px`,
  margin: `0px`,
});

const InformationIcon: any = styled('img')({
  height: `24px`,
  width: `24px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Icon2: any = styled('img')({
  height: `10px`,
  width: `13px`,
  position: `absolute`,
  left: `6px`,
  top: `8px`,
});

const Q4580: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `-0.5px`,
  textDecoration: `none`,
  lineHeight: `28px`,
  textTransform: `none`,
  margin: `0px 0px 0px 10px`,
});

const Frame143751: any = styled('div')({
  borderRadius: `10px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `5px 10px`,
  boxSizing: `border-box`,
  width: `357px`,
  left: `73px`,
  top: `0px`,
});

const Safeway: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `-0.5px`,
  textDecoration: `none`,
  lineHeight: `28px`,
  textTransform: `none`,
  margin: `0px`,
});

const Cell1: any = styled('div')({
  backdropFilter: `blur(48.59000015258789px)`,
  WebkitBackdropFilter: `blur(48.59000015258789px)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `110px`,
  width: `580px`,
  margin: `12px 0px 0px 0px`,
});

const Background1: any = styled('div')({
  backgroundColor: `rgba(251, 251, 251, 1)`,
  border: `1px solid rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  width: `580px`,
  height: `110px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Frame143791: any = styled('div')({
  opacity: `0.800000011920929`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `0px`,
  top: `63px`,
});

const Frame143781: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Group2894302: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `38px`,
  width: `580px`,
  margin: `0px`,
});

const Frame892: any = styled('div')({
  borderRadius: `10px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-end`,
  padding: `5px 10px`,
  boxSizing: `border-box`,
  width: `72.63px`,
  left: `0px`,
  top: `0px`,
});

const Today: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `-0.5px`,
  textDecoration: `none`,
  lineHeight: `28px`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame143762: any = styled('div')({
  borderRadius: `10px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-end`,
  padding: `5px 15px`,
  boxSizing: `border-box`,
  width: `124.51px`,
  left: `455px`,
  top: `0px`,
});

const Q11524: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `-0.5px`,
  textDecoration: `none`,
  lineHeight: `28px`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame143752: any = styled('div')({
  borderRadius: `10px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `5px 10px`,
  boxSizing: `border-box`,
  width: `382.86px`,
  left: `73px`,
  top: `0px`,
});

const DrKavrojivkMedicalOf: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `-0.5px`,
  textDecoration: `none`,
  lineHeight: `28px`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame143861: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `556px`,
  left: `12px`,
  top: `12px`,
});

const Icon3: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  height: `40px`,
  margin: `0px`,
});

const Bitmap1: any = styled('div')({
  backgroundColor: `rgba(118, 118, 118, 1)`,
  borderRadius: `100px`,
  width: `40px`,
  height: `40px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Group2894671: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `362px`,
  height: `40px`,
  margin: `0px 0px 0px 15px`,
});

const Title1: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `600`,
  fontSize: `20px`,
  letterSpacing: `-0.4099999964237213px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  opacity: `0.800000011920929`,
  width: `331px`,
  height: `20.51px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Text2: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 0.5)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `-0.20999999344348907px`,
  textDecoration: `none`,
  lineHeight: `120.00000476837158%`,
  textTransform: `none`,
  width: `362px`,
  height: `22.56px`,
  position: `absolute`,
  left: `0px`,
  top: `17px`,
});

const MembersAdd2: any = styled(MembersAdd)(({ theme }: any) => ({
  width: `100px`,
  position: `absolute`,
  left: `456px`,
  top: `0px`,
}));

function MainPanelThreadsAllB(props: MainPanelThreadsAllBProps): JSX.Element {
  return (
    <MainPanelThreadsAllB1 className={props.className}>
      <Group289454>
        <AiCoach>
          <Group289373>
            <ChatGptFlyout>
              <Rectangle4125></Rectangle4125>
            </ChatGptFlyout>
          </Group289373>
        </AiCoach>
        <Group289416>
          <Group289391>
            <Group289369>
              <Text>{`Back`}</Text>
            </Group289369>
          </Group289391>
        </Group289416>
        <Group289387
          src={Group289387Image}
          loading="lazy"
          alt={'Group 289387'}
        />
      </Group289454>
      <Cell>
        <Background></Background>
        <Frame14386>
          <Icon1>
            <Bitmap></Bitmap>
          </Icon1>
          <Group289467>
            <Title>{`Grocery`}</Title>
            <Text1>
              {`@Naomi is there are way to split the cost of the recent market trip`}
            </Text1>
          </Group289467>
          <MembersAdd1 />
        </Frame14386>
        <Frame14379>
          <Frame14378>
            <Group289430>
              <Frame89>
                <Aug9>{`Aug 9`}</Aug9>
              </Frame89>
              <Frame14376>
                <Q25792>{`$257.92`}</Q25792>
              </Frame14376>
              <Frame14375>
                <WholeFoodsMarket>{`Whole Foods Market`}</WholeFoodsMarket>
              </Frame14375>
            </Group289430>
          </Frame14378>
          <Group2894301>
            <Frame891>
              <Aug3>{`Aug 3`}</Aug3>
            </Frame891>
            <Frame143761>
              <Checkbox1>
                <InformationIcon
                  src={InformationIconImage}
                  loading="lazy"
                  alt={'Information Icon'}
                />
                <Icon2 src={Icon2Image} loading="lazy" alt={'Icon'} />
              </Checkbox1>
              <Q4580>{`$45.80`}</Q4580>
            </Frame143761>
            <Frame143751>
              <Safeway>{`Safeway`}</Safeway>
            </Frame143751>
          </Group2894301>
        </Frame14379>
      </Cell>
      <Cell1>
        <Background1></Background1>
        <Frame143791>
          <Frame143781>
            <Group2894302>
              <Frame892>
                <Today>{`Today`}</Today>
              </Frame892>
              <Frame143762>
                <Q11524>{`$115.24`}</Q11524>
              </Frame143762>
              <Frame143752>
                <DrKavrojivkMedicalOf>
                  {`Dr. Kavrojivk Medical Offices`}
                </DrKavrojivkMedicalOf>
              </Frame143752>
            </Group2894302>
          </Frame143781>
        </Frame143791>
        <Frame143861>
          <Icon3>
            <Bitmap1></Bitmap1>
          </Icon3>
          <Group2894671>
            <Title1>{`Healthcare`}</Title1>
            <Text2>{`Shared`}</Text2>
          </Group2894671>
          <MembersAdd2 />
        </Frame143861>
      </Cell1>
    </MainPanelThreadsAllB1>
  );
}

export default MainPanelThreadsAllB;
