/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Iphone1ComponentImagImage from 'src/assets/images/Card_iphone_1_component_image_.png';
import { styled } from '@mui/material/styles';
import { CardProps } from 'src/types';

const Card1: any = styled('div')({
  backgroundColor: `rgba(245, 245, 245, 1)`,
  boxShadow: `0px 2px 2px rgba(0, 0, 0, 0.12)`,
  border: `1px solid rgba(125, 178, 178, 1)`,
  boxSizing: `border-box`,
  borderRadius: `12px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `138px`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `6px 19px 6px 22px`,
  overflow: `hidden`,
});

const Frame2: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `229px`,
  height: `103px`,
  margin: `0px`,
});

const Image1: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `54px`,
  height: `51px`,
  margin: `0px`,
});

const Iphone1ComponentImag: any = styled('img')({
  height: `51px`,
  width: `54px`,
  objectFit: `cover`,
  alignSelf: `stretch`,
  flex: `1`,
  margin: `0px`,
});

const TextStack: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `4px 0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 16px`,
});

const Rectangle4: any = styled('div')({
  backgroundColor: `rgba(125, 178, 178, 1)`,
  borderRadius: `0px`,
  height: `2px`,
  width: `136px`,
  margin: `0px`,
});

const IPhoneXiiComponentIn: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Maitree`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `4px 0px 0px 0px`,
});

const DescriptionComponent: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Maitree`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `116.00000858306885%`,
  textTransform: `none`,
  height: `55px`,
  width: `136px`,
  margin: `4px 0px 0px 0px`,
});

const PropertyStack: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-end`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Q34500ComponentInput: any = styled('div')({
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(66, 120, 208, 1)`,
  fontStyle: `normal`,
  fontFamily: `Maitree`,
  fontWeight: `500`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Q12ComponentInputTex: any = styled('div')({
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Maitree`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `10px 0px 0px 0px`,
});

const Q4550ComponentInputT: any = styled('div')({
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Maitree`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `10px 0px 0px 0px`,
});

function Card(props: CardProps): JSX.Element {
  return (
    <Card1 className={props.className}>
      <Frame2>
        <Image1>
          <Iphone1ComponentImag
            src={Iphone1ComponentImagImage}
            loading="lazy"
            alt={'iphone 1[component:image]'}
          />
        </Image1>
        <TextStack>
          <Rectangle4></Rectangle4>
          <IPhoneXiiComponentIn>{`iPhone XII`}</IPhoneXiiComponentIn>
          <DescriptionComponent>
            {`An apple mobile which is nothing like apple`}
          </DescriptionComponent>
        </TextStack>
      </Frame2>
      <PropertyStack>
        <Q34500ComponentInput>{`$345.00`}</Q34500ComponentInput>
        <Q12ComponentInputTex>{`-12%`}</Q12ComponentInputTex>
        <Q4550ComponentInputT>{`4.5 / 5.0`}</Q4550ComponentInputT>
      </PropertyStack>
    </Card1>
  );
}

export default Card;
