/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import ShapeImage from 'src/assets/images/DropdownPanelGrocery_Shape.png';
import PathImage from 'src/assets/images/DropdownPanelGrocery_Path.png';
import Chart3Image from 'src/assets/images/DropdownPanelGrocery_Chart.png';
import { styled } from '@mui/material/styles';
import MagiconsGlyphArrowArrowDown2 from 'src/components/MagiconsGlyphArrowArrowDown2/MagiconsGlyphArrowArrowDown2';
import MembersAdd from 'src/components/MembersAdd/MembersAdd';
import AssetsSeparatorEmpty from 'src/components/AssetsSeparatorEmpty/AssetsSeparatorEmpty';
import { DropdownPanelGroceryProps } from 'src/types';

const DropdownPanelGrocery1: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `40px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
  height: 'auto',
  width: 'fit-content',
});

const BudgetDropdown: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `24px 12px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const InputField: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(170, 170, 170, 1)`,
  boxSizing: `border-box`,
  borderRadius: `16px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `12px 16px`,
  width: `390px`,
  margin: `0px`,
}));

const Frame283: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Grocery: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(13, 14, 15, 1)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `18px`,
  textTransform: `none`,
  margin: `0px`,
}));

const MagiconsGlyphArrowAr: any = styled(MagiconsGlyphArrowArrowDown2)(
  ({ theme }: any) => ({
    width: `32px`,
    height: `32px`,
    margin: `0px`,
  })
);

const BudgetProgress: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `12px 12px 0px 12px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const MonthlyAllocation: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(37, 37, 37, 1)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `135.0000023841858%`,
  textTransform: `none`,
  width: `338px`,
  margin: `0px`,
});

const Frame14324: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `390px`,
  margin: `10px 0px 0px 0px`,
});

const Balance: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(37, 37, 37, 1)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `600`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `150%`,
  textTransform: `none`,
  margin: `0px`,
});

const Q67: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(37, 37, 37, 1)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `150%`,
  textTransform: `none`,
  margin: `0px`,
});

const Chart: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `48px`,
  width: `390px`,
  margin: `10px 0px 0px 0px`,
});

const Rectangle: any = styled('div')({
  backgroundColor: `rgba(0, 0, 0, 0.4)`,
  backdropFilter: `blur(48.58625411987305px)`,
  WebkitBackdropFilter: `blur(48.58625411987305px)`,
  borderRadius: `10px`,
  width: `390px`,
  height: `48px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Right: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `80.23px`,
  height: `18px`,
  left: `296px`,
  top: `25px`,
});

const Q66: any = styled('div')(({ theme }: any) => ({
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro Text`,
  fontWeight: `400`,
  fontSize: `13px`,
  letterSpacing: `-0.07999999821186066px`,
  textDecoration: `none`,
  lineHeight: `18px`,
  textTransform: `none`,
  width: `80.23px`,
  height: `18px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Left: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `91.17px`,
  height: `18px`,
  left: `12px`,
  top: `25px`,
});

const Done: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro Text`,
  fontWeight: `600`,
  fontSize: `13px`,
  letterSpacing: `-0.07999999821186066px`,
  textDecoration: `none`,
  lineHeight: `18px`,
  textTransform: `none`,
  width: `39.31px`,
  position: `absolute`,
  left: `52px`,
  top: `0px`,
}));

const Q8Of12: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro Text`,
  fontWeight: `400`,
  fontSize: `13px`,
  letterSpacing: `-0.07999999821186066px`,
  textDecoration: `none`,
  lineHeight: `18px`,
  textTransform: `none`,
  width: `56.65px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Chart1: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `366.17px`,
  height: `10px`,
  left: `12px`,
  top: `11px`,
});

const Shape: any = styled('img')({
  height: `10px`,
  width: `142.63px`,
  position: `absolute`,
  left: `224px`,
  top: `0px`,
});

const Path: any = styled('img')({
  height: `10px`,
  width: `222.86px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const MembersWDescription: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `12px 0px 24px 0px`,
  boxSizing: `border-box`,
  height: `58px`,
  width: `390px`,
  margin: `10px 0px 0px 0px`,
});

const MembersAdd1: any = styled(MembersAdd)(({ theme }: any) => ({
  width: `123px`,
  margin: `0px`,
}));

const Frame14386: any = styled('div')({
  borderRadius: `20px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `5px 15px 5px 0px`,
  boxSizing: `border-box`,
  width: `231px`,
  margin: `0px 0px 0px 15px`,
});

const YouSarahAndPauloShar: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 0.5)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `400`,
  fontSize: `11px`,
  letterSpacing: `-0.04509999960660935px`,
  textDecoration: `none`,
  lineHeight: `150%`,
  textTransform: `none`,
  flex: `1`,
  height: `23px`,
  margin: `0px`,
});

const ExtensionsChartsMone: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `10px 12px`,
  boxSizing: `border-box`,
  height: `352px`,
  margin: `0px`,
});

const Frame143241: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `390px`,
  margin: `0px`,
});

const HistoricCosts: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(37, 37, 37, 1)`,
  fontStyle: `normal`,
  fontFamily: `Wells Fargo Sans`,
  fontWeight: `600`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `150%`,
  textTransform: `none`,
  margin: `0px`,
});

const Background: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `300px`,
  width: `390px`,
  margin: `10px 0px 0px 0px`,
});

const Background1: any = styled('div')({
  borderRadius: `0px`,
  width: `390px`,
  height: `300px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Separator: any = styled(AssetsSeparatorEmpty)(({ theme }: any) => ({
  width: `390px`,
  height: `300px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Chart2: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `29px`,
  top: `43px`,
});

const Chart3: any = styled('img')({
  height: `248px`,
  width: `356.72px`,
  margin: `0px`,
});

const Numbers: any = styled('div')({
  opacity: `0.30000001192092896`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `10px 0px 0px 0px`,
});

const Frame289471: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `356.36px`,
  margin: `0px`,
});

const Q1233: any = styled('div')(({ theme }: any) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro Text`,
  fontWeight: `400`,
  fontSize: `13px`,
  letterSpacing: `-0.07999999821186066px`,
  textDecoration: `none`,
  lineHeight: `18px`,
  textTransform: `none`,
  width: `25.68px`,
  margin: `0px`,
}));

const Q1243: any = styled('div')(({ theme }: any) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro Text`,
  fontWeight: `400`,
  fontSize: `13px`,
  letterSpacing: `-0.07999999821186066px`,
  textDecoration: `none`,
  lineHeight: `18px`,
  textTransform: `none`,
  width: `23.54px`,
  margin: `0px 0px 0px 42px`,
}));

const Q1253: any = styled('div')(({ theme }: any) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro Text`,
  fontWeight: `400`,
  fontSize: `13px`,
  letterSpacing: `-0.07999999821186066px`,
  textDecoration: `none`,
  lineHeight: `18px`,
  textTransform: `none`,
  width: `27.82px`,
  margin: `0px 0px 0px 42px`,
}));

const Q1303: any = styled('div')(({ theme }: any) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro Text`,
  fontWeight: `400`,
  fontSize: `13px`,
  letterSpacing: `-0.07999999821186066px`,
  textDecoration: `none`,
  lineHeight: `18px`,
  textTransform: `none`,
  width: `23.54px`,
  margin: `0px 0px 0px 42px`,
}));

const Q1313: any = styled('div')(({ theme }: any) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro Text`,
  fontWeight: `400`,
  fontSize: `13px`,
  letterSpacing: `-0.07999999821186066px`,
  textDecoration: `none`,
  lineHeight: `18px`,
  textTransform: `none`,
  width: `19.26px`,
  margin: `0px 0px 0px 42px`,
}));

const Q1323: any = styled('div')(({ theme }: any) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro Text`,
  fontWeight: `400`,
  fontSize: `13px`,
  letterSpacing: `-0.07999999821186066px`,
  textDecoration: `none`,
  lineHeight: `18px`,
  textTransform: `none`,
  width: `25.68px`,
  margin: `0px 0px 0px 42px`,
}));

const Tag: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `22px`,
  width: `70px`,
  left: `41px`,
  top: `208px`,
});

const Frame289469: any = styled('div')({
  backgroundColor: `rgba(229, 229, 234, 1)`,
  borderRadius: `14px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `2px 8px`,
  boxSizing: `border-box`,
  left: `0px`,
  top: `0px`,
  overflow: `hidden`,
});

const Q1164072: any = styled('div')(({ theme }: any) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro Text`,
  fontWeight: `600`,
  fontSize: `13px`,
  letterSpacing: `-0.07999999821186066px`,
  textDecoration: `none`,
  lineHeight: `18px`,
  textTransform: `uppercase`,
  opacity: `0.5`,
  margin: `0px`,
}));

const Tag1: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `22px`,
  width: `74px`,
  left: `232px`,
  top: `17px`,
});

const Frame289470: any = styled('div')({
  backgroundColor: `rgba(229, 229, 234, 1)`,
  borderRadius: `14px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `2px 8px`,
  boxSizing: `border-box`,
  left: `0px`,
  top: `0px`,
  overflow: `hidden`,
});

const Q11640721: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `SF Pro Text`,
  fontWeight: `600`,
  fontSize: `13px`,
  letterSpacing: `-0.07999999821186066px`,
  textDecoration: `none`,
  lineHeight: `18px`,
  textTransform: `uppercase`,
  opacity: `0.5`,
  margin: `0px`,
}));

function DropdownPanelGrocery(props: DropdownPanelGroceryProps): JSX.Element {
  return (
    <DropdownPanelGrocery1 className={props.className}>
      <BudgetDropdown>
        <InputField>
          <Frame283>
            <Grocery>{`Grocery`}</Grocery>
            <MagiconsGlyphArrowAr />
          </Frame283>
        </InputField>
      </BudgetDropdown>
      <BudgetProgress>
        <MonthlyAllocation>{`Monthly Allocation`}</MonthlyAllocation>
        <Frame14324>
          <Balance>{`Balance`}</Balance>
          <Q67>{`67%`}</Q67>
        </Frame14324>
        <Chart>
          <Rectangle></Rectangle>
          <Right>
            <Q66>{`19 days left`}</Q66>
          </Right>
          <Left>
            <Done>{`$900`}</Done>
            <Q8Of12>{`$620 of`}</Q8Of12>
          </Left>
          <Chart1>
            <Shape src={ShapeImage} loading="lazy" alt={'Shape'} />
            <Path src={PathImage} loading="lazy" alt={'Path'} />
          </Chart1>
        </Chart>
        <MembersWDescription>
          <MembersAdd1 />
          <Frame14386>
            <YouSarahAndPauloShar>
              {`You, Sarah and Paulo share this budget`}
            </YouSarahAndPauloShar>
          </Frame14386>
        </MembersWDescription>
      </BudgetProgress>
      <ExtensionsChartsMone>
        <Frame143241>
          <HistoricCosts>{`Historic Costs`}</HistoricCosts>
        </Frame143241>
        <Background>
          <Background1></Background1>
          {false && <Separator />}
        </Background>
        <Chart2>
          <Chart3 src={Chart3Image} loading="lazy" alt={'Chart'} />
          <Numbers>
            <Frame289471>
              <Q1233>{`Mar`}</Q1233>
              <Q1243>{`Apr`}</Q1243>
              <Q1253>{`May`}</Q1253>
              <Q1303>{`Jun`}</Q1303>
              <Q1313>{`Jul`}</Q1313>
              <Q1323>{`Aug`}</Q1323>
            </Frame289471>
          </Numbers>
          <Tag>
            <Frame289469>
              <Q1164072>{`$640.72`}</Q1164072>
            </Frame289469>
          </Tag>
          <Tag1>
            <Frame289470>
              <Q11640721>{`$ 928.20`}</Q11640721>
            </Frame289470>
          </Tag1>
        </Chart2>
      </ExtensionsChartsMone>
    </DropdownPanelGrocery1>
  );
}

export default DropdownPanelGrocery;
